#include "wled.h"

#ifndef WLED_DISABLE_ESPNOW

#ifdef ARDUINO_ARCH_ESP32
#include <freertos/FreeRTOS.h>
#include <freertos/queue.h>
#endif

// AI: below section was generated by an AI
/*
 * ESP-NOW semantic command flood.
 *
 * Frames are deliberately compact and contain only the commands used by the remote app.
 * Every participating WLED relays a new frame, while origin/session/sequence deduplication
 * prevents loops. All multi-byte fields are little-endian because every supported ESP target
 * is little-endian. ESP-NOW supplies the per-link frame CRC.
 * Design source: WLED's existing QuickEspNow broadcast transport and sync-group semantics in
 * udp.cpp; the controlled-flood identity, hop limit, retry, and jitter logic is original here.
 */
namespace {
  constexpr uint8_t ESP_NOW_FLOOD_MAGIC_0 = 'W';
  constexpr uint8_t ESP_NOW_FLOOD_MAGIC_1 = 'F';
  constexpr uint8_t ESP_NOW_FLOOD_VERSION = 2;
  constexpr uint8_t ESP_NOW_FLOOD_TYPE_COMMAND = 1;
  constexpr uint8_t ESP_NOW_FLOOD_TYPE_TIME = 2;
  constexpr uint8_t ESP_NOW_FLOOD_COMMAND_PRESET = 0x01;
  constexpr uint8_t ESP_NOW_FLOOD_COMMAND_POWER = 0x02;
  constexpr uint8_t ESP_NOW_FLOOD_COMMAND_BRIGHTNESS = 0x04;
  constexpr uint8_t ESP_NOW_FLOOD_COMMAND_FLAGS = ESP_NOW_FLOOD_COMMAND_PRESET | ESP_NOW_FLOOD_COMMAND_POWER | ESP_NOW_FLOOD_COMMAND_BRIGHTNESS;
  constexpr uint8_t ESP_NOW_FLOOD_MAX_HOPS = 32;
  constexpr uint8_t ESP_NOW_FLOOD_COMMAND_REPEATS = 3;
  constexpr uint8_t ESP_NOW_FLOOD_TIME_REPEATS = 2;
  constexpr uint8_t ESP_NOW_FLOOD_RX_QUEUE_SIZE = 12;
  constexpr uint8_t ESP_NOW_FLOOD_TX_SLOTS = 4;
  constexpr uint8_t ESP_NOW_FLOOD_SEEN_SLOTS = 16;
  constexpr uint8_t ESP_NOW_FLOOD_ORDER_SLOTS = 4;
  constexpr uint8_t ESP_NOW_FLOOD_APPLY_SLOTS = 8;
  constexpr uint8_t ESP_NOW_FLOOD_STRATUM_NONE = 255;
  constexpr uint32_t ESP_NOW_FLOOD_REPEAT_DELAY_MS = 24;
  constexpr uint32_t ESP_NOW_FLOOD_TIME_INTERVAL_MS = 5000;
  constexpr uint32_t ESP_NOW_FLOOD_MASTER_TIMEOUT_MS = 15000;
  constexpr uint32_t ESP_NOW_FLOOD_ELECTION_JITTER_MS = 100;
  constexpr uint32_t ESP_NOW_FLOOD_PENDING_TIMEOUT_MS = 3000;
  constexpr int32_t ESP_NOW_FLOOD_LINK_DELAY_MS = 1;
  constexpr int32_t ESP_NOW_FLOOD_CLOCK_DEADBAND_MS = 1;
  constexpr int32_t ESP_NOW_FLOOD_CLOCK_SLEW_MS = 1;
  constexpr int32_t ESP_NOW_FLOOD_CLOCK_STEP_THRESHOLD_MS = 50;

  struct __attribute__((packed)) EspNowFloodCommand {
    uint8_t flags;
    uint8_t preset;
    uint8_t brightness;
    uint8_t power;
  };

  struct __attribute__((packed)) EspNowFloodPacket {
    uint8_t magic[2];
    uint8_t version;
    uint8_t type;
    uint32_t session;
    uint32_t sequence;
    uint32_t senderTime;
    uint32_t effectEpoch;
    uint32_t wallSeconds;
    uint16_t wallMillis;
    uint8_t origin[6];
    uint32_t masterSession;
    uint8_t masterOrigin[6];
    uint8_t masterStratum;
    uint8_t groups;
    uint8_t hopsRemaining;
    uint8_t payloadLength;
    uint8_t payload[sizeof(EspNowFloodCommand)];
  };

  constexpr size_t ESP_NOW_FLOOD_HEADER_SIZE = offsetof(EspNowFloodPacket, payload);
  static_assert(sizeof(EspNowFloodPacket) <= 250, "ESP-NOW flood frame exceeds the ESP-NOW payload limit");

  struct EspNowFloodIngress {
    EspNowFloodPacket packet;
    uint32_t receivedAt;
    uint8_t length;
    bool local;
  };

  struct EspNowFloodTx {
    EspNowFloodPacket packet;
    uint8_t length;
    uint8_t sendsRemaining;
    uint32_t nextSend;
    uint32_t order;
    bool active;
  };

  struct EspNowFloodSeen {
    uint8_t origin[6];
    uint32_t session;
    uint32_t sequence;
    bool valid;
  };

  struct EspNowFloodOrder {
    uint8_t origin[6];
    uint32_t session;
    uint32_t presetSequence;
    uint32_t powerSequence;
    uint32_t brightnessSequence;
    uint8_t validFlags;
    bool valid;
  };

  struct EspNowFloodApply {
    EspNowFloodPacket packet;
    uint32_t order;
    bool active;
  };

#ifdef ARDUINO_ARCH_ESP32
  QueueHandle_t espNowFloodRxQueue = nullptr;
#else
  EspNowFloodIngress espNowFloodRxQueue[ESP_NOW_FLOOD_RX_QUEUE_SIZE];
  volatile uint8_t espNowFloodRxHead = 0;
  volatile uint8_t espNowFloodRxTail = 0;
#endif

  EspNowFloodTx espNowFloodTx[ESP_NOW_FLOOD_TX_SLOTS] = {};
  EspNowFloodSeen espNowFloodSeen[ESP_NOW_FLOOD_SEEN_SLOTS] = {};
  EspNowFloodSeen espNowFloodQueued[ESP_NOW_FLOOD_SEEN_SLOTS] = {};
  EspNowFloodOrder espNowFloodOrder[ESP_NOW_FLOOD_ORDER_SLOTS] = {};
  EspNowFloodApply espNowFloodApply[ESP_NOW_FLOOD_APPLY_SLOTS] = {};
  uint8_t espNowFloodSeenNext = 0;
  uint8_t espNowFloodQueuedNext = 0;
  uint8_t espNowFloodOrderNext = 0;
  uint32_t espNowFloodTxOrder = 0;
  uint32_t espNowFloodApplyOrder = 0;
  int32_t espNowFloodClockOffset = 0;
  uint32_t espNowFloodLocalSession = 0;
  uint8_t espNowFloodMasterOrigin[6] = {};
  uint32_t espNowFloodMasterSession = 0;
  uint8_t espNowFloodMasterStratum = ESP_NOW_FLOOD_STRATUM_NONE;
  uint8_t espNowFloodWallStratum = ESP_NOW_FLOOD_STRATUM_NONE;
  uint32_t espNowFloodSequence = 0;
  uint32_t espNowFloodLastClockSeen = 0;
  uint32_t espNowFloodLastSuperiorSeen = 0;
  uint32_t espNowFloodNextTimeSend = 0;
  uint32_t espNowFloodPendingEpoch = 0;
  uint32_t espNowFloodPendingUntil = 0;
  uint8_t espNowFloodPendingPreset = 0;
  bool espNowFloodClockValid = false;
  bool espNowFloodTimeMaster = false;
  bool espNowFloodInitialized = false;

  // Returns a random non-zero session or starting sequence identifier.
  uint32_t espNowFloodRandomId() {
    uint32_t value = hw_random();
    return value ? value : 1;
  }

  // Returns the local view of the shared wrap-safe monotonic network clock.
  uint32_t espNowFloodNetworkMillis() {
    return millis() + espNowFloodClockOffset;
  }

  // Returns this node's distance from an independent wall-clock source.
  uint8_t espNowFloodLocalWallStratum() {
    const uint8_t source = toki.getTimeSource();
    if (source == TOKI_TS_NONE) return ESP_NOW_FLOOD_STRATUM_NONE;
    if (source == TOKI_TS_UDP || source == TOKI_TS_UDP_SEC || source == TOKI_TS_UDP_NTP) return espNowFloodWallStratum;
    return 0;
  }

  // Refreshes a time beacon's wall-clock sample immediately before radio send.
  void espNowFloodStampWallTime(EspNowFloodPacket& packet) {
    if (packet.type != ESP_NOW_FLOOD_TYPE_TIME || packet.masterStratum == ESP_NOW_FLOOD_STRATUM_NONE || toki.getTimeSource() == TOKI_TS_NONE) {
      packet.wallSeconds = 0;
      packet.wallMillis = 0;
      return;
    }
    const Toki::Time wallTime = toki.getTime();
    packet.wallSeconds = wallTime.sec;
    packet.wallMillis = wallTime.ms;
  }

  // Advances a relayed beacon's root-authored wall sample to its actual send instant.
  void espNowFloodAdvanceWallTime(EspNowFloodPacket& packet, uint32_t senderTime) {
    if (packet.type != ESP_NOW_FLOOD_TYPE_TIME || packet.masterStratum == ESP_NOW_FLOOD_STRATUM_NONE) return;
    Toki::Time wallTime = {packet.wallSeconds, packet.wallMillis};
    toki.adjust(wallTime, int32_t(senderTime - packet.senderTime));
    packet.wallSeconds = wallTime.sec;
    packet.wallMillis = wallTime.ms;
  }

  // Aligns WLED's effect clock to an epoch expressed in shared network time.
  void espNowFloodAlignEffectEpoch(uint32_t effectEpoch) {
    if (isClockSyncedPlaylistActive()) return;
    const uint32_t effectTime = espNowFloodNetworkMillis() - effectEpoch;
    strip.timebase = effectTime - millis();
  }

  // Rejects zero, multicast, and broadcast identities at the raw ESP-NOW ingress.
  bool espNowFloodValidOrigin(const uint8_t* origin) {
    if (origin[0] & 0x01) return false;
    uint8_t combined = 0;
    for (uint8_t index = 0; index < 6; index++) combined |= origin[index];
    return combined != 0;
  }

  // Adds a validated frame to the callback-to-loop queue without blocking the Wi-Fi task.
  bool espNowFloodQueueIngress(const EspNowFloodPacket& packet, uint8_t length, bool local) {
    EspNowFloodIngress ingress = {packet, millis(), length, local};
  #ifdef ARDUINO_ARCH_ESP32
    return espNowFloodRxQueue && xQueueSend(espNowFloodRxQueue, &ingress, 0) == pdTRUE;
  #else
    const uint8_t next = (espNowFloodRxHead + 1U) % ESP_NOW_FLOOD_RX_QUEUE_SIZE;
    if (next == espNowFloodRxTail) return false;
    espNowFloodRxQueue[espNowFloodRxHead] = ingress;
    espNowFloodRxHead = next;
    return true;
  #endif
  }

  // Removes one queued frame for processing in the main loop.
  bool espNowFloodTakeIngress(EspNowFloodIngress& ingress) {
  #ifdef ARDUINO_ARCH_ESP32
    return espNowFloodRxQueue && xQueueReceive(espNowFloodRxQueue, &ingress, 0) == pdTRUE;
  #else
    if (espNowFloodRxTail == espNowFloodRxHead) return false;
    ingress = espNowFloodRxQueue[espNowFloodRxTail];
    espNowFloodRxTail = (espNowFloodRxTail + 1U) % ESP_NOW_FLOOD_RX_QUEUE_SIZE;
    return true;
  #endif
  }

  // Checks and records the immutable identity of a frame to stop flood loops.
  bool espNowFloodAlreadySeen(const EspNowFloodPacket& packet) {
    for (const EspNowFloodSeen& seen : espNowFloodSeen) {
      if (seen.valid && seen.session == packet.session && seen.sequence == packet.sequence && memcmp(seen.origin, packet.origin, sizeof(seen.origin)) == 0) return true;
    }

    EspNowFloodSeen& seen = espNowFloodSeen[espNowFloodSeenNext];
    memcpy(seen.origin, packet.origin, sizeof(seen.origin));
    seen.session = packet.session;
    seen.sequence = packet.sequence;
    seen.valid = true;
    espNowFloodSeenNext = (espNowFloodSeenNext + 1U) % ESP_NOW_FLOOD_SEEN_SLOTS;
    return false;
  }

  // Checks callback-side identities so redundant copies cannot crowd out distinct commands.
  bool espNowFloodAlreadyQueued(const EspNowFloodPacket& packet) {
    for (const EspNowFloodSeen& queued : espNowFloodQueued) {
      if (queued.valid && queued.session == packet.session && queued.sequence == packet.sequence && memcmp(queued.origin, packet.origin, sizeof(queued.origin)) == 0) return true;
    }
    return false;
  }

  // Records an identity only after its first copy was admitted to the main-loop queue.
  void espNowFloodRememberQueued(const EspNowFloodPacket& packet) {
    EspNowFloodSeen& queued = espNowFloodQueued[espNowFloodQueuedNext];
    memcpy(queued.origin, packet.origin, sizeof(queued.origin));
    queued.session = packet.session;
    queued.sequence = packet.sequence;
    queued.valid = true;
    espNowFloodQueuedNext = (espNowFloodQueuedNext + 1U) % ESP_NOW_FLOOD_SEEN_SLOTS;
  }

  // Compares a frame's clock-master identity with the currently followed master.
  bool espNowFloodSameMaster(const EspNowFloodPacket& packet) {
    return espNowFloodMasterSession == packet.masterSession && memcmp(espNowFloodMasterOrigin, packet.masterOrigin, sizeof(espNowFloodMasterOrigin)) == 0;
  }

  // Breaks partition-root ties deterministically so a reunited network converges once.
  bool espNowFloodCandidatePreferred(const EspNowFloodPacket& packet) {
    if (packet.masterStratum != espNowFloodMasterStratum) return packet.masterStratum < espNowFloodMasterStratum;
    const int originOrder = memcmp(packet.masterOrigin, espNowFloodMasterOrigin, sizeof(espNowFloodMasterOrigin));
    return originOrder < 0 || (originOrder == 0 && packet.masterSession != espNowFloodMasterSession);
  }

  // Reports whether a packet's root outranks this controller in the bully election.
  bool espNowFloodRootOutranksLocal(const EspNowFloodPacket& packet) {
    const uint8_t localStratum = espNowFloodLocalWallStratum();
    if (packet.masterStratum != localStratum) return packet.masterStratum < localStratum;
    uint8_t localOrigin[6];
    WiFi.macAddress(localOrigin);
    return memcmp(packet.masterOrigin, localOrigin, sizeof(localOrigin)) < 0;
  }

  // Adopts a packet's master and disciplines the monotonic clock without steady-state jumps.
  void espNowFloodAdoptClock(const EspNowFloodPacket& packet, uint32_t receivedAt) {
    const bool masterChanged = !espNowFloodSameMaster(packet);
    if (masterChanged) {
      memcpy(espNowFloodMasterOrigin, packet.masterOrigin, sizeof(espNowFloodMasterOrigin));
      espNowFloodMasterSession = packet.masterSession;
      espNowFloodMasterStratum = packet.masterStratum;
      espNowFloodTimeMaster = false;
      // Do not leak queued beacons from the superseded root into the reunited network.
      for (EspNowFloodTx& slot : espNowFloodTx) {
        if (slot.active && slot.packet.type == ESP_NOW_FLOOD_TYPE_TIME) slot.active = false;
      }
    }

    const uint32_t localNetworkTime = espNowFloodNetworkMillis();
    // Account for callback-to-main-loop queue time so it does not accumulate at every hop.
    const uint32_t receiveQueueDelay = millis() - receivedAt;
    int32_t error = int32_t(packet.senderTime + ESP_NOW_FLOOD_LINK_DELAY_MS + receiveQueueDelay - localNetworkTime);
    if (masterChanged || !espNowFloodClockValid || error < -ESP_NOW_FLOOD_CLOCK_STEP_THRESHOLD_MS || error > ESP_NOW_FLOOD_CLOCK_STEP_THRESHOLD_MS) {
      espNowFloodClockOffset += error;
    } else if (error < -ESP_NOW_FLOOD_CLOCK_DEADBAND_MS) {
      espNowFloodClockOffset -= ESP_NOW_FLOOD_CLOCK_SLEW_MS;
    } else if (error > ESP_NOW_FLOOD_CLOCK_DEADBAND_MS) {
      espNowFloodClockOffset += ESP_NOW_FLOOD_CLOCK_SLEW_MS;
    }
    espNowFloodClockValid = true;
    espNowFloodLastClockSeen = millis();
  }

  // Adopts a time beacon's wall clock and records its ESP-NOW hop distance.
  void espNowFloodAdoptWallTime(const EspNowFloodPacket& packet, uint32_t receivedAt) {
    if (packet.masterStratum == ESP_NOW_FLOOD_STRATUM_NONE) return;
    const uint8_t source = toki.getTimeSource();
    const bool directSource = source != TOKI_TS_NONE && source != TOKI_TS_UDP && source != TOKI_TS_UDP_SEC && source != TOKI_TS_UDP_NTP;
    // Preserve direct-source eligibility while making every node follow the elected wall clock.
    const uint8_t adoptedSource = directSource ? source : TOKI_TS_UDP_NTP;

    Toki::Time wallTime = {packet.wallSeconds, packet.wallMillis};
    const uint32_t receiveQueueDelay = millis() - receivedAt;
    toki.adjust(wallTime, ESP_NOW_FLOOD_LINK_DELAY_MS + receiveQueueDelay);

    const Toki::Time localWallTime = toki.getTime();
    const int64_t error = (int64_t(wallTime.sec) - localWallTime.sec) * 1000LL + int32_t(wallTime.ms) - localWallTime.ms;
    if (source == TOKI_TS_NONE || espNowFloodWallStratum == ESP_NOW_FLOOD_STRATUM_NONE || error < -ESP_NOW_FLOOD_CLOCK_STEP_THRESHOLD_MS || error > ESP_NOW_FLOOD_CLOCK_STEP_THRESHOLD_MS) {
      toki.setTime(wallTime, adoptedSource);
    } else if (error < -ESP_NOW_FLOOD_CLOCK_DEADBAND_MS) {
      Toki::Time corrected = localWallTime;
      toki.adjust(corrected, -ESP_NOW_FLOOD_CLOCK_SLEW_MS);
      toki.setTime(corrected, adoptedSource);
    } else if (error > ESP_NOW_FLOOD_CLOCK_DEADBAND_MS) {
      Toki::Time corrected = localWallTime;
      toki.adjust(corrected, ESP_NOW_FLOOD_CLOCK_SLEW_MS);
      toki.setTime(corrected, adoptedSource);
    }

    const uint16_t distance = uint16_t(packet.masterStratum) + ESP_NOW_FLOOD_MAX_HOPS - packet.hopsRemaining + 1U;
    espNowFloodWallStratum = distance < ESP_NOW_FLOOD_STRATUM_NONE ? distance : ESP_NOW_FLOOD_STRATUM_NONE - 1U;
  }

  // Chooses a transmit slot, preferring to evict a time beacon rather than a command.
  EspNowFloodTx* espNowFloodFindTxSlot(uint8_t type) {
    for (EspNowFloodTx& slot : espNowFloodTx) if (!slot.active) return &slot;
    if (type == ESP_NOW_FLOOD_TYPE_COMMAND) {
      for (EspNowFloodTx& slot : espNowFloodTx) if (slot.packet.type == ESP_NOW_FLOOD_TYPE_TIME) return &slot;
    }
    return nullptr;
  }

  // Schedules redundant transmissions with a small relay jitter to reduce collisions.
  bool espNowFloodScheduleTx(const EspNowFloodPacket& packet, uint8_t length, bool relay) {
    EspNowFloodTx* slot = espNowFloodFindTxSlot(packet.type);
    if (!slot) return false;
    slot->packet = packet;
    slot->length = length;
    slot->sendsRemaining = packet.type == ESP_NOW_FLOOD_TYPE_COMMAND ? ESP_NOW_FLOOD_COMMAND_REPEATS : ESP_NOW_FLOOD_TIME_REPEATS;
    slot->nextSend = millis() + (relay ? random(7, 22) : 0);
    slot->order = ++espNowFloodTxOrder;
    slot->active = true;
    return true;
  }

  // Creates the common header for a frame originated by this controller.
  EspNowFloodPacket espNowFloodCreatePacket(uint8_t type, uint8_t payloadLength) {
    EspNowFloodPacket packet = {};
    packet.magic[0] = ESP_NOW_FLOOD_MAGIC_0;
    packet.magic[1] = ESP_NOW_FLOOD_MAGIC_1;
    packet.version = ESP_NOW_FLOOD_VERSION;
    packet.type = type;
    WiFi.macAddress(packet.origin);
    packet.session = espNowFloodLocalSession;
    packet.sequence = ++espNowFloodSequence;
    packet.senderTime = espNowFloodNetworkMillis();
    if (espNowFloodTimeMaster) espNowFloodMasterStratum = espNowFloodLocalWallStratum();
    memcpy(packet.masterOrigin, espNowFloodMasterOrigin, sizeof(packet.masterOrigin));
    packet.masterSession = espNowFloodMasterSession;
    packet.masterStratum = espNowFloodMasterStratum;
    espNowFloodStampWallTime(packet);
    packet.groups = syncGroups;
    packet.hopsRemaining = ESP_NOW_FLOOD_MAX_HOPS;
    packet.payloadLength = payloadLength;
    return packet;
  }

  // Starts or resumes this controller as the network clock master after an app command.
  void espNowFloodBecomeTimeMaster() {
    if (!espNowFloodTimeMaster) {
      espNowFloodMasterSession = espNowFloodLocalSession;
      espNowFloodMasterStratum = espNowFloodLocalWallStratum();
      for (EspNowFloodTx& slot : espNowFloodTx) {
        if (slot.active && slot.packet.type == ESP_NOW_FLOOD_TYPE_TIME) slot.active = false;
      }
    }
    WiFi.macAddress(espNowFloodMasterOrigin);
    espNowFloodClockValid = true;
    espNowFloodTimeMaster = true;
    espNowFloodLastClockSeen = millis();
    espNowFloodNextTimeSend = millis() + ESP_NOW_FLOOD_TIME_INTERVAL_MS;
  }

  // Records the effect epoch to apply after the direct state update or asynchronous preset load.
  void espNowFloodPrepareTimebase(uint32_t effectEpoch, uint8_t preset) {
    espNowFloodPendingEpoch = effectEpoch;
    espNowFloodPendingPreset = preset;
    espNowFloodPendingUntil = millis() + ESP_NOW_FLOOD_PENDING_TIMEOUT_MS;
  }

  // Validates the complete semantic command before a frame is queued, relayed, or applied.
  bool espNowFloodReadCommand(const EspNowFloodPacket& packet, EspNowFloodCommand& command) {
    if (packet.payloadLength != sizeof(EspNowFloodCommand)) return false;
    memcpy(&command, packet.payload, sizeof(command));
    if (!command.flags || command.flags & ~ESP_NOW_FLOOD_COMMAND_FLAGS) return false;
    if ((command.flags & ESP_NOW_FLOOD_COMMAND_PRESET) && (command.preset == 0 || command.preset > 250)) return false;
    if ((command.flags & ESP_NOW_FLOOD_COMMAND_POWER) && command.power > 1) return false;
    return true;
  }

  // Finds the bounded per-origin ordering state used to reject delayed command fields.
  EspNowFloodOrder* espNowFloodFindOrder(const EspNowFloodPacket& packet, bool create) {
    for (EspNowFloodOrder& order : espNowFloodOrder) {
      if (order.valid && order.session == packet.session && memcmp(order.origin, packet.origin, sizeof(order.origin)) == 0) return &order;
    }
    if (!create) return nullptr;

    for (EspNowFloodOrder& order : espNowFloodOrder) {
      if (order.valid) continue;
      memcpy(order.origin, packet.origin, sizeof(order.origin));
      order.session = packet.session;
      order.valid = true;
      return &order;
    }

    EspNowFloodOrder& order = espNowFloodOrder[espNowFloodOrderNext];
    order = {};
    memcpy(order.origin, packet.origin, sizeof(order.origin));
    order.session = packet.session;
    order.valid = true;
    espNowFloodOrderNext = (espNowFloodOrderNext + 1U) % ESP_NOW_FLOOD_ORDER_SLOTS;
    return &order;
  }

  // Removes fields superseded by a later sequence while retaining independent commands.
  void espNowFloodFilterStaleCommand(const EspNowFloodPacket& packet, EspNowFloodCommand& command) {
    EspNowFloodOrder* order = espNowFloodFindOrder(packet, false);
    if (!order) return;
    if ((command.flags & ESP_NOW_FLOOD_COMMAND_PRESET) && (order->validFlags & ESP_NOW_FLOOD_COMMAND_PRESET) && int32_t(packet.sequence - order->presetSequence) <= 0) command.flags &= ~ESP_NOW_FLOOD_COMMAND_PRESET;
    if ((command.flags & ESP_NOW_FLOOD_COMMAND_POWER) && (order->validFlags & ESP_NOW_FLOOD_COMMAND_POWER) && int32_t(packet.sequence - order->powerSequence) <= 0) command.flags &= ~ESP_NOW_FLOOD_COMMAND_POWER;
    if ((command.flags & ESP_NOW_FLOOD_COMMAND_BRIGHTNESS) && (order->validFlags & ESP_NOW_FLOOD_COMMAND_BRIGHTNESS) && int32_t(packet.sequence - order->brightnessSequence) <= 0) command.flags &= ~ESP_NOW_FLOOD_COMMAND_BRIGHTNESS;
  }

  // Records accepted fields and stops retries fully replaced by the newer command.
  void espNowFloodRememberCommand(const EspNowFloodPacket& packet, const EspNowFloodCommand& command) {
    EspNowFloodOrder* order = espNowFloodFindOrder(packet, true);
    if (!order) return;
    if (command.flags & ESP_NOW_FLOOD_COMMAND_PRESET) order->presetSequence = packet.sequence;
    if (command.flags & ESP_NOW_FLOOD_COMMAND_POWER) order->powerSequence = packet.sequence;
    if (command.flags & ESP_NOW_FLOOD_COMMAND_BRIGHTNESS) order->brightnessSequence = packet.sequence;
    order->validFlags |= command.flags;

    for (EspNowFloodTx& slot : espNowFloodTx) {
      if (!slot.active || slot.packet.type != ESP_NOW_FLOOD_TYPE_COMMAND || slot.packet.session != packet.session || memcmp(slot.packet.origin, packet.origin, sizeof(packet.origin)) != 0 || int32_t(packet.sequence - slot.packet.sequence) <= 0) continue;
      EspNowFloodCommand pending;
      if (espNowFloodReadCommand(slot.packet, pending) && !(pending.flags & ~command.flags)) slot.active = false;
    }
  }

  // Validates and applies a semantic command once, outside the ESP-NOW callback context.
  void espNowFloodApplyCommand(const EspNowFloodPacket& packet) {
    EspNowFloodCommand command;
    if (!espNowFloodReadCommand(packet, command)) return;

    StaticJsonDocument<96> doc;
    JsonObject root = doc.to<JsonObject>();
    if (command.flags & ESP_NOW_FLOOD_COMMAND_PRESET) root[F("ps")] = command.preset;
    if (command.flags & ESP_NOW_FLOOD_COMMAND_POWER) root["on"] = bool(command.power);
    if (command.flags & ESP_NOW_FLOOD_COMMAND_BRIGHTNESS) root["bri"] = command.brightness;

    espNowFloodPrepareTimebase(packet.effectEpoch, command.flags & ESP_NOW_FLOOD_COMMAND_PRESET ? command.preset : 0);
    deserializeState(root, CALL_MODE_NO_NOTIFY);
    if (!(command.flags & ESP_NOW_FLOOD_COMMAND_PRESET)) applyESPNowFloodTimebase();
  }

  // Queues commands behind an asynchronous preset while preserving cross-field order.
  bool espNowFloodQueueApply(const EspNowFloodPacket& packet) {
    EspNowFloodCommand command;
    if (!espNowFloodReadCommand(packet, command)) return false;

    for (EspNowFloodApply& slot : espNowFloodApply) {
      if (!slot.active || slot.packet.session != packet.session || memcmp(slot.packet.origin, packet.origin, sizeof(packet.origin)) != 0 || int32_t(packet.sequence - slot.packet.sequence) <= 0) continue;
      EspNowFloodCommand pending;
      if (espNowFloodReadCommand(slot.packet, pending) && !(pending.flags & ~command.flags)) slot.active = false;
    }

    for (EspNowFloodApply& slot : espNowFloodApply) {
      if (slot.active) continue;
      slot.packet = packet;
      slot.order = ++espNowFloodApplyOrder;
      slot.active = true;
      return true;
    }
    DEBUG_PRINTLN(F("ESP-NOW flood apply queue full."));
    return false;
  }

  // Applies immediately unless a preceding asynchronous preset is still loading.
  void espNowFloodApplyOrQueueCommand(const EspNowFloodPacket& packet) {
    if (espNowFloodPendingPreset && espNowFloodPendingUntil && int32_t(millis() - espNowFloodPendingUntil) < 0) {
      espNowFloodQueueApply(packet);
      return;
    }
    espNowFloodPendingPreset = 0;
    espNowFloodPendingUntil = 0;
    espNowFloodApplyCommand(packet);
  }

  // Drains one deferred command after its preceding preset has completed or timed out.
  void espNowFloodServiceApply() {
    if (espNowFloodPendingPreset && espNowFloodPendingUntil && int32_t(millis() - espNowFloodPendingUntil) < 0) return;
    espNowFloodPendingPreset = 0;
    espNowFloodPendingUntil = 0;

    EspNowFloodApply* selected = nullptr;
    for (EspNowFloodApply& slot : espNowFloodApply) {
      if (slot.active && (!selected || int32_t(slot.order - selected->order) < 0)) selected = &slot;
    }
    if (!selected) return;
    selected->active = false;
    espNowFloodApplyCommand(selected->packet);
  }

  // Processes a unique local or received frame and schedules its bounded relay transmissions.
  void espNowFloodProcessIngress(const EspNowFloodIngress& ingress) {
    const EspNowFloodPacket& packet = ingress.packet;
    if (!packet.groups || (!(receiveGroups & packet.groups) && !ingress.local)) return;
    if (espNowFloodAlreadySeen(packet)) return;

    EspNowFloodCommand command = {};
    if (packet.type == ESP_NOW_FLOOD_TYPE_COMMAND) {
      if (!espNowFloodReadCommand(packet, command)) return;
      espNowFloodFilterStaleCommand(packet, command);
      if (!command.flags) return;
      espNowFloodRememberCommand(packet, command);
    }

    if (ingress.local) {
      espNowFloodScheduleTx(packet, ingress.length, false);
      if (packet.type == ESP_NOW_FLOOD_TYPE_COMMAND) {
        EspNowFloodPacket effectivePacket = packet;
        memcpy(effectivePacket.payload, &command, sizeof(command));
        espNowFloodApplyOrQueueCommand(effectivePacket);
      }
      return;
    }

    // Only a lower-MAC root suppresses this node's own election deadline.
    if (espNowFloodRootOutranksLocal(packet)) espNowFloodLastSuperiorSeen = millis();

    if (packet.type == ESP_NOW_FLOOD_TYPE_COMMAND) {
      const bool masterExpired = millis() - espNowFloodLastClockSeen > ESP_NOW_FLOOD_MASTER_TIMEOUT_MS;
      const bool clockAccepted = espNowFloodSameMaster(packet) || !espNowFloodClockValid || masterExpired || espNowFloodCandidatePreferred(packet);
      if (clockAccepted) espNowFloodAdoptClock(packet, ingress.receivedAt);
    } else if (packet.type == ESP_NOW_FLOOD_TYPE_TIME) {
      const bool masterExpired = millis() - espNowFloodLastClockSeen > ESP_NOW_FLOOD_MASTER_TIMEOUT_MS;
      if (!espNowFloodSameMaster(packet) && espNowFloodClockValid && !masterExpired && !espNowFloodCandidatePreferred(packet)) return;
      espNowFloodAdoptClock(packet, ingress.receivedAt);
      espNowFloodAdoptWallTime(packet, ingress.receivedAt);
      espNowFloodAlignEffectEpoch(packet.effectEpoch);
    } else {
      return;
    }

    if (packet.hopsRemaining > 0) {
      EspNowFloodPacket relay = packet;
      relay.hopsRemaining--;
      espNowFloodScheduleTx(relay, ingress.length, true);
    }
    if (packet.type == ESP_NOW_FLOOD_TYPE_COMMAND) {
      EspNowFloodPacket effectivePacket = packet;
      memcpy(effectivePacket.payload, &command, sizeof(command));
      espNowFloodApplyOrQueueCommand(effectivePacket);
    }
  }

  // Sends one native ESP-NOW broadcast without waiting for a completion callback.
  bool espNowFloodSend(const uint8_t* data, uint8_t length) {
  #ifdef ARDUINO_ARCH_ESP32
    if (!esp_now_is_peer_exist(ESPNOW_BROADCAST_ADDRESS)) {
      esp_now_peer_info_t peer = {};
      memcpy(peer.peer_addr, ESPNOW_BROADCAST_ADDRESS, ESP_NOW_ETH_ALEN);
      peer.channel = 0; // Follow the radio's current Wi-Fi channel.
      peer.ifidx = apActive ? WIFI_IF_AP : WIFI_IF_STA;
      peer.encrypt = false;
      const esp_err_t addResult = esp_now_add_peer(&peer);
      if (addResult != ESP_OK && addResult != ESP_ERR_ESPNOW_EXIST) return false;
    }
    // QuickESPNow's asynchronous TX task busy-spins if the SDK loses a send
    // callback during a radio transition. Native submission is non-blocking and
    // lets this bounded retry scheduler provide reliability without that failure.
    return esp_now_send(ESPNOW_BROADCAST_ADDRESS, data, length) == ESP_OK;
  #else
    return quickEspNow.send(ESPNOW_BROADCAST_ADDRESS, data, length) == COMMS_SEND_OK;
  #endif
  }

  // Sends at most one due retry per loop so the radio queue cannot be overrun.
  void espNowFloodServiceTx() {
    if (statusESPNow != ESP_NOW_STATE_ON) return;
    const uint32_t now = millis();

    EspNowFloodTx* commandSlot = nullptr;
    for (EspNowFloodTx& slot : espNowFloodTx) {
      if (!slot.active || slot.packet.type != ESP_NOW_FLOOD_TYPE_COMMAND) continue;
      if (!commandSlot || int32_t(slot.order - commandSlot->order) < 0) commandSlot = &slot;
    }

    EspNowFloodTx* selected = commandSlot;
    if (!selected) {
      for (EspNowFloodTx& slot : espNowFloodTx) {
        if (slot.active && slot.packet.type == ESP_NOW_FLOOD_TYPE_TIME && (!selected || int32_t(slot.order - selected->order) < 0)) selected = &slot;
      }
    }
    if (!selected || int32_t(now - selected->nextSend) < 0) return;

    const uint32_t senderTime = espNowFloodNetworkMillis();
    espNowFloodAdvanceWallTime(selected->packet, senderTime);
    selected->packet.senderTime = senderTime;
    if (!espNowFloodSend(reinterpret_cast<const uint8_t*>(&selected->packet), selected->length)) {
      selected->nextSend = now + ESP_NOW_FLOOD_REPEAT_DELAY_MS;
      DEBUG_PRINTLN(F("ESP-NOW flood send deferred."));
      return;
    }
    if (--selected->sendsRemaining == 0) selected->active = false;
    else selected->nextSend = now + ESP_NOW_FLOOD_REPEAT_DELAY_MS + random(0, 9);
  }

  // Originates the periodic clock frame that keeps long-running effects phase-aligned.
  void espNowFloodSendTimeIfDue() {
    if (!espNowFloodTimeMaster || int32_t(millis() - espNowFloodNextTimeSend) < 0) return;
    EspNowFloodPacket packet = espNowFloodCreatePacket(ESP_NOW_FLOOD_TYPE_TIME, 0);
    packet.effectEpoch = espNowFloodNetworkMillis() - (millis() + strip.timebase);
    const uint8_t length = ESP_NOW_FLOOD_HEADER_SIZE;
    if (espNowFloodQueueIngress(packet, length, true)) {
      espNowFloodLastClockSeen = millis();
      espNowFloodNextTimeSend = millis() + ESP_NOW_FLOOD_TIME_INTERVAL_MS;
    }
  }

  // Elects a replacement after a partition loses contact with its previous root.
  void espNowFloodElectIfOrphaned() {
    if (espNowFloodTimeMaster || millis() - espNowFloodLastSuperiorSeen <= ESP_NOW_FLOOD_MASTER_TIMEOUT_MS) return;
    espNowFloodBecomeTimeMaster();
    espNowFloodNextTimeSend = millis() + random(ESP_NOW_FLOOD_ELECTION_JITTER_MS + 1);
  }
}

// Initializes the bounded callback queue whenever the ESP-NOW radio stack starts.
void initESPNowFlood() {
#ifdef ARDUINO_ARCH_ESP32
  if (!espNowFloodRxQueue) espNowFloodRxQueue = xQueueCreate(ESP_NOW_FLOOD_RX_QUEUE_SIZE, sizeof(EspNowFloodIngress));
  else xQueueReset(espNowFloodRxQueue);
  espNowFloodInitialized = espNowFloodRxQueue != nullptr;
#else
  espNowFloodRxHead = 0;
  espNowFloodRxTail = 0;
  espNowFloodInitialized = true;
#endif
  memset(espNowFloodTx, 0, sizeof(espNowFloodTx));
  memset(espNowFloodSeen, 0, sizeof(espNowFloodSeen));
  memset(espNowFloodQueued, 0, sizeof(espNowFloodQueued));
  memset(espNowFloodOrder, 0, sizeof(espNowFloodOrder));
  memset(espNowFloodApply, 0, sizeof(espNowFloodApply));
  espNowFloodSeenNext = 0;
  espNowFloodQueuedNext = 0;
  espNowFloodOrderNext = 0;
  espNowFloodTxOrder = 0;
  espNowFloodApplyOrder = 0;
  espNowFloodClockOffset = 0;
  espNowFloodLocalSession = espNowFloodRandomId();
  espNowFloodSequence = espNowFloodRandomId();
  memset(espNowFloodMasterOrigin, 0, sizeof(espNowFloodMasterOrigin));
  espNowFloodMasterSession = 0;
  espNowFloodClockValid = false;
  espNowFloodTimeMaster = false;
  espNowFloodMasterStratum = ESP_NOW_FLOOD_STRATUM_NONE;
  espNowFloodWallStratum = ESP_NOW_FLOOD_STRATUM_NONE;
  espNowFloodLastClockSeen = millis();
  espNowFloodLastSuperiorSeen = millis();
  espNowFloodPendingUntil = 0;
  espNowFloodPendingEpoch = 0;
  espNowFloodPendingPreset = 0;
}

// Stops flood activity while preserving the allocated ESP32 queue for the next reconnect.
void deinitESPNowFlood() {
  espNowFloodInitialized = false;
  espNowFloodTimeMaster = false;
  memset(espNowFloodTx, 0, sizeof(espNowFloodTx));
  memset(espNowFloodApply, 0, sizeof(espNowFloodApply));
  espNowFloodPendingUntil = 0;
  espNowFloodPendingPreset = 0;
#ifdef ARDUINO_ARCH_ESP32
  if (espNowFloodRxQueue) xQueueReset(espNowFloodRxQueue);
#else
  espNowFloodRxHead = 0;
  espNowFloodRxTail = 0;
#endif
}

// Recognizes, strictly validates, and queues a raw ESP-NOW flood frame.
bool receiveESPNowFloodPacket(const uint8_t* data, uint8_t len, bool broadcast) {
  if (!data || len < 2 || data[0] != ESP_NOW_FLOOD_MAGIC_0 || data[1] != ESP_NOW_FLOOD_MAGIC_1) return false;
  if (!espNowFloodInitialized || !broadcast || !enableESPNow || !useESPNowSync || len < ESP_NOW_FLOOD_HEADER_SIZE || len > sizeof(EspNowFloodPacket)) return true;

  EspNowFloodPacket packet = {};
  memcpy(&packet, data, len);
  if (packet.version != ESP_NOW_FLOOD_VERSION || packet.hopsRemaining > ESP_NOW_FLOOD_MAX_HOPS || packet.payloadLength > sizeof(packet.payload) || len != ESP_NOW_FLOOD_HEADER_SIZE + packet.payloadLength) return true;
  if (!packet.session || !packet.masterSession || (packet.masterStratum != ESP_NOW_FLOOD_STRATUM_NONE && packet.wallMillis >= 1000) || !espNowFloodValidOrigin(packet.origin) || !espNowFloodValidOrigin(packet.masterOrigin)) return true;
  if ((packet.type == ESP_NOW_FLOOD_TYPE_COMMAND && packet.payloadLength != sizeof(EspNowFloodCommand)) || (packet.type == ESP_NOW_FLOOD_TYPE_TIME && packet.payloadLength != 0)) return true;
  if (packet.type != ESP_NOW_FLOOD_TYPE_COMMAND && packet.type != ESP_NOW_FLOOD_TYPE_TIME) return true;
  if (packet.type == ESP_NOW_FLOOD_TYPE_COMMAND) {
    EspNowFloodCommand command;
    if (!espNowFloodReadCommand(packet, command)) return true;
  }

  if (espNowFloodAlreadyQueued(packet)) return true;
  if (!espNowFloodQueueIngress(packet, len, false)) {
    DEBUG_PRINTLN(F("ESP-NOW flood receive queue full."));
  } else {
    espNowFloodRememberQueued(packet);
  }
  return true;
}

// Extracts the remote app's supported JSON fields and originates one semantic flood command.
bool sendESPNowFloodCommand(JsonObject root) {
  if (!espNowFloodInitialized || !enableESPNow || !useESPNowSync || statusESPNow != ESP_NOW_STATE_ON || !syncGroups) return false;

  EspNowFloodCommand command = {};
  if (!root[F("ps")].isNull()) {
    if (!root[F("ps")].is<int>()) return false;
    const int preset = root[F("ps")].as<int>();
    if (preset < 1 || preset > 250) return false;
    command.flags |= ESP_NOW_FLOOD_COMMAND_PRESET;
    command.preset = preset;
  }
  if (!root["on"].isNull()) {
    if (!root["on"].is<bool>()) return false;
    command.flags |= ESP_NOW_FLOOD_COMMAND_POWER;
    command.power = root["on"].as<bool>();
  }
  if (!root["bri"].isNull()) {
    if (!root["bri"].is<int>()) return false;
    const int brightness = root["bri"].as<int>();
    if (brightness < 0 || brightness > 255) return false;
    command.flags |= ESP_NOW_FLOOD_COMMAND_BRIGHTNESS;
    command.brightness = brightness;
  }
  if (!command.flags) return false;

  const bool masterExpired = !espNowFloodTimeMaster && millis() - espNowFloodLastClockSeen > ESP_NOW_FLOOD_MASTER_TIMEOUT_MS;
  if (!espNowFloodClockValid || masterExpired) espNowFloodBecomeTimeMaster();
  EspNowFloodPacket packet = espNowFloodCreatePacket(ESP_NOW_FLOOD_TYPE_COMMAND, sizeof(command));
  packet.effectEpoch = espNowFloodNetworkMillis();
  memcpy(packet.payload, &command, sizeof(command));
  if (!espNowFloodQueueIngress(packet, sizeof(packet), true)) return false;
  return true;
}

// Promotes a controller with direct wall time and schedules a fresh beacon immediately.
void useESPNowFloodLocalTimeSource() {
  if (!espNowFloodInitialized || !enableESPNow || !useESPNowSync || statusESPNow != ESP_NOW_STATE_ON || !syncGroups || toki.getTimeSource() == TOKI_TS_NONE) return;
  espNowFloodBecomeTimeMaster();
  espNowFloodMasterStratum = espNowFloodLocalWallStratum();
  for (EspNowFloodTx& slot : espNowFloodTx) {
    if (slot.active && slot.packet.type == ESP_NOW_FLOOD_TYPE_TIME) slot.active = false;
  }
  espNowFloodNextTimeSend = millis();
}

// Applies the pending common effect epoch after a direct command or matching preset load.
void applyESPNowFloodTimebase(uint8_t presetId) {
  if (!espNowFloodPendingUntil) return;
  if (int32_t(millis() - espNowFloodPendingUntil) >= 0) {
    espNowFloodPendingUntil = 0;
    return;
  }
  if (presetId != espNowFloodPendingPreset) {
    if (presetId == 0) espNowFloodPendingUntil = 0;
    return;
  }

  espNowFloodAlignEffectEpoch(espNowFloodPendingEpoch);
  espNowFloodPendingUntil = 0;
  espNowFloodPendingPreset = 0;
}

// Runs flood receive, clock-beacon, relay, and retry work from WLED's main loop.
void handleESPNowFlood() {
  if (!espNowFloodInitialized || !enableESPNow || !useESPNowSync || statusESPNow != ESP_NOW_STATE_ON) return;
  EspNowFloodIngress ingress;
  for (uint8_t count = 0; count < ESP_NOW_FLOOD_RX_QUEUE_SIZE && espNowFloodTakeIngress(ingress); count++) espNowFloodProcessIngress(ingress);
  espNowFloodServiceApply();
  espNowFloodElectIfOrphaned();
  espNowFloodSendTimeIfDue();
  espNowFloodServiceTx();
}

// AI: end

#endif
