#include "wled.h"

class LedWesteUsermod : public Usermod
{
public:
    static const char mode_circle_str[] PROGMEM;
    static void mode_circle();

    static const char mode_blinking_stripe_str[] PROGMEM;
    static void mode_blinking_stripe();

    static const char mode_barber_pole_str[] PROGMEM;
    static void mode_barber_pole();

    // AI: below section was generated by an AI
    static const char mode_heart_aura_str[] PROGMEM;
    static void mode_heart_aura();

    static const char mode_heart_orbit_str[] PROGMEM;
    static void mode_heart_orbit();

    static const char mode_heart_echoes_str[] PROGMEM;
    static void mode_heart_echoes();
    // AI: end

    void setup() override
    {
        strip.addEffect(255, &mode_circle, mode_circle_str);
        strip.addEffect(255, &mode_blinking_stripe, mode_blinking_stripe_str);
        strip.addEffect(255, &mode_barber_pole, mode_barber_pole_str);
        strip.addEffect(255, &mode_heart_aura, mode_heart_aura_str);
        strip.addEffect(255, &mode_heart_orbit, mode_heart_orbit_str);
        strip.addEffect(255, &mode_heart_echoes, mode_heart_echoes_str);
    }

    void loop() override
    {
    }
};

// Break light
const char LedWesteUsermod::mode_circle_str[] = "Circle@,Softness,Center X,Center Y,Radius;!,!;;2;ix=0,c1=0,c2=14,c3=7";
void LedWesteUsermod::mode_circle()
{
    const auto fg = SEGCOLOR(0);
    const auto bg = SEGCOLOR(1);

    const int cx = int(SEGMENT.custom1) - 1;
    const int cy = int(SEGMENT.custom2) - 1;
    const int radius = SEGMENT.custom3;
    const int softness = SEGMENT.intensity >> 5;

    SEGMENT.fill(bg);

    const int radius2 = radius * radius;
    const auto floorDiv2 = [](int v) {
        return v >= 0 ? v / 2 : -((-v + 1) / 2);
    };
    const int edgeRadius = radius + softness;
    const int minX = floorDiv2(cx - edgeRadius) - 1;
    const int maxX = floorDiv2(cx + edgeRadius) + 1;
    const int minY = floorDiv2(cy - edgeRadius) - 1;
    const int maxY = floorDiv2(cy + edgeRadius) + 1;

    for (int y = minY; y <= maxY; y++)
    {
        const int dy = (y << 1) - cy;
        for (int x = minX; x <= maxX; x++)
        {
            const int dx = (x << 1) - cx;
            const int distance2 = dx * dx + dy * dy;
            if (distance2 <= radius2) {
                SEGMENT.setPixelColorXY(x, y, fg);
            } else if (softness && distance2 <= edgeRadius * edgeRadius) {
                const float distance = sqrtf(float(distance2));
                const uint8_t blend = constrain(int((float(edgeRadius) - distance) * 255.0f / softness), 0, 255);
                SEGMENT.setPixelColorXY(x, y, color_blend(bg, fg, blend));
            }
        }
    }
}

// Blinking vertical stripe
const char LedWesteUsermod::mode_blinking_stripe_str[] = "Blinking Stripe@!,Duty cycle,Begin,End,Run-in;!,!;;2;c1=2,c2=7";
void LedWesteUsermod::mode_blinking_stripe()
{
    const auto width = SEGMENT.virtualWidth();
    const auto height = SEGMENT.virtualHeight();

    const int xStart = SEGMENT.custom1;
    const int xStop = SEGMENT.custom2;
    const auto runIn = SEGMENT.custom3;
    const bool stripeWrapsX = SEGMENT.wrap_x && width > 0 && xStart > xStop;

    const auto fg = SEGCOLOR(0);
    const auto bg = SEGCOLOR(1);

    const uint32_t variableCycleTime = (255 - SEGMENT.speed) * 20;
    const uint32_t minimumPhaseTime = FRAMETIME;
    const uint32_t cycleTime = max(variableCycleTime, minimumPhaseTime * 2U);
    const uint32_t requestedOnTime = (variableCycleTime * SEGMENT.intensity) >> 8;
    const uint32_t onTime = constrain(requestedOnTime, minimumPhaseTime, cycleTime - minimumPhaseTime);
    uint32_t const rem = strip.now % cycleTime;
    const bool on = SEGMENT.speed == 0 || rem <= onTime;

    const auto wrappedDistance = [width](int from, int to) {
        int distance = (to - from) % width;
        if (distance < 0) distance += width;
        return distance;
    };
    const int stripeWidth = stripeWrapsX ? wrappedDistance(xStart, xStop) : max(0, xStop - xStart);
    const int maxDepth = stripeWidth / 2;
    int depth = maxDepth;
    if (runIn > 0) {
        depth = (maxDepth + 1) * rem * 31 / (runIn * onTime);
    }

    SEGMENT.fill(bg);
    if (on)
    {
        depth = min(depth, maxDepth);
        for (int xDepth = 0; xDepth <= depth; ++xDepth)
        {
            for (int y = 0; y < height; ++y)
            {
                SEGMENT.setPixelColorXY(xStart + xDepth, y, fg);
                SEGMENT.setPixelColorXY(xStop - xDepth, y, fg);
            }
        }
    }
}

// AI: below section was generated by an AI
// Palette barber pole
const char LedWesteUsermod::mode_barber_pole_str[] = "Barber Pole@Speed,Scale,Angle;!;!;2;pal=5,sx=70,ix=80,c1=128";
void LedWesteUsermod::mode_barber_pole()
{
    struct BarberPoleState {
        uint16_t phaseOffset;
        uint8_t lastSpeed;
        uint16_t lastYStep;
        uint16_t lastXStep;
        uint16_t lastXCycles;
        bool lastWrapX;
    };

    const int width = SEGMENT.virtualWidth();
    const int height = SEGMENT.virtualHeight();
    if (width <= 0 || height <= 0) {
        return;
    }
    if (!SEGENV.allocateData(sizeof(BarberPoleState))) {
        return;
    }
    auto& state = *reinterpret_cast<BarberPoleState*>(SEGENV.data);

    const uint16_t phaseStep = 4 + (SEGMENT.intensity >> 2);
    const uint16_t angle = ((uint32_t)SEGMENT.custom1 * 16384U + 127U) / 255U;
    int32_t xComponent = sin16_t(angle);
    int32_t yComponent = cos16_t(angle);
    if (xComponent < 0) xComponent = 0;
    if (yComponent < 0) yComponent = 0;
    const uint16_t requestedXStep = ((uint32_t)phaseStep * xComponent + 16383U) / 32767U;
    const uint16_t yStep = ((uint32_t)phaseStep * yComponent + 16383U) / 32767U;
    uint16_t xCycles = ((uint32_t)requestedXStep * width + 128U) >> 8;
    if (requestedXStep && xCycles == 0) {
        xCycles = 1;
    }

    if (SEGENV.call == 0) {
        state.phaseOffset = 0;
        state.lastSpeed = SEGMENT.speed;
        state.lastYStep = yStep;
        state.lastXStep = requestedXStep;
        state.lastXCycles = xCycles;
        state.lastWrapX = SEGMENT.wrap_x;
    } else if (state.lastSpeed != SEGMENT.speed || state.lastYStep != yStep || state.lastXStep != requestedXStep || state.lastXCycles != xCycles || state.lastWrapX != SEGMENT.wrap_x) {
        const int xRef = width >> 1;
        const int yRef = height >> 1;
        const uint16_t oldXPhase = state.lastWrapX ? ((uint32_t)xRef * state.lastXCycles * 256U) / width
                                                   : xRef * state.lastXStep;
        const uint16_t newXPhase = SEGMENT.wrap_x ? ((uint32_t)xRef * xCycles * 256U) / width
                                                  : xRef * requestedXStep;
        const uint16_t oldTimePhase = ((uint32_t)strip.now * state.lastSpeed) >> 8;
        const uint16_t newTimePhase = ((uint32_t)strip.now * SEGMENT.speed) >> 8;
        state.phaseOffset += oldTimePhase + oldXPhase + yRef * state.lastYStep
                           - newTimePhase - newXPhase - yRef * yStep;
        state.lastSpeed = SEGMENT.speed;
        state.lastYStep = yStep;
        state.lastXStep = requestedXStep;
        state.lastXCycles = xCycles;
        state.lastWrapX = SEGMENT.wrap_x;
    }

    const uint16_t timePhase = (((uint32_t)strip.now * SEGMENT.speed) >> 8) + state.phaseOffset;

    for (int y = 0; y < height; ++y)
    {
        const uint16_t yPhase = y * yStep + timePhase;
        for (int x = 0; x < width; ++x)
        {
            const uint16_t xPhase = SEGMENT.wrap_x ? ((uint32_t)x * xCycles * 256U) / width
                                                   : x * requestedXStep;
            SEGMENT.setPixelColorXY(x, y, SEGMENT.color_from_palette(xPhase + yPhase, false, true, 255));
        }
    }
}

namespace {

constexpr float HEART_CENTER_Y = 0.55f;
constexpr float HEART_HALF_X = 0.70f;
constexpr float HEART_HALF_Y = 0.65f;

// Returns the signed distance to a normalized heart. Negative values are inside.
// Shape algorithm adapted from Inigo Quilez's 2D distance functions:
// https://iquilezles.org/articles/distfunctions2d/
static float heartDistance(float dx, float dy, float halfWidth, float halfHeight, bool* carvedNotch = nullptr)
{
  const float px = fabsf(dx) * HEART_HALF_X / halfWidth;
  const float py = HEART_CENTER_Y - dy * HEART_HALF_Y / halfHeight;

  float distance;
  if (px + py > 1.0f) {
    const float qx = px - 0.25f;
    const float qy = py - 0.75f;
    distance = sqrtf(qx * qx + qy * qy) - 0.3535534f;
  } else {
    const float diagonal = max(px + py, 0.0f) * 0.5f;
    const float topDistance2 = px * px + (py - 1.0f) * (py - 1.0f);
    const float tipX = px - diagonal;
    const float tipY = py - diagonal;
    const float tipDistance2 = tipX * tipX + tipY * tipY;
    distance = sqrtf(min(topDistance2, tipDistance2));
    if (px < py) distance = -distance;
  }

  // The mathematical heart's cleft is sub-pixel on a 15-row matrix. Widen it
  // into a short V so the two round lobes remain separate at garment resolution.
  const float notch = py - 0.78f - px * 1.5f;
  if (carvedNotch) *carvedNotch = notch > 0.0f;
  if (notch > 0.0f) distance = max(distance, 0.14f + notch * 0.5f);
  return distance;
}

// Finds the shortest horizontal distance on a cylindrical matrix.
static float wrappedDelta(float x, float center, float width)
{
  float delta = x - center;
  const float halfWidth = width * 0.5f;
  if (delta > halfWidth) delta -= width;
  if (delta < -halfWidth) delta += width;
  return delta;
}

// Produces a natural lub-dub envelope with a smaller, closely-spaced second beat.
static uint8_t heartbeatLevel(uint32_t now, uint8_t speed)
{
  const uint16_t bpm = 42U + ((uint16_t)speed * 78U >> 8);
  const uint16_t period = 60000U / bpm;
  const uint8_t phase = ((now % period) * 256U) / period;

  const auto pulseAt = [phase](uint8_t center, uint8_t radius) {
    int distance = abs(int(phase) - int(center));
    if (distance > 128) distance = 256 - distance;
    if (distance >= radius) return uint8_t(0);
    return ease8InOutCubic(((radius - distance) * 255U) / radius);
  };

  const uint8_t first = pulseAt(8, 22);
  const uint8_t second = scale8_video(pulseAt(55, 17), 190);
  return max(first, second);
}

// Builds a dim, flowing palette field so unlit heart areas remain animated.
static uint32_t flowingBackground(int x, int y, uint16_t timePhase, uint8_t amount)
{
  const uint8_t wave = sin8_t(uint8_t(x * 17 - y * 11 + timePhase));
  const uint8_t shimmer = scale8_video(qsub8(wave, 112), amount);
  const uint8_t paletteIndex = uint8_t(x * 13 + y * 7 + timePhase);
  return color_blend(SEGCOLOR(1), SEGMENT.color_from_palette(paletteIndex, false, true, 0), shimmer);
}

} // namespace

// A breathing heart with a double-beat flash, aura, and an expanding echo wave.
const char LedWesteUsermod::mode_heart_aura_str[] = "Heart Aura@!,Glow,Size,Color flow;!,!;!;2;pal=11,sx=92,ix=170,c1=160,c2=95";
void LedWesteUsermod::mode_heart_aura()
{
  const int width = SEGMENT.virtualWidth();
  const int height = SEGMENT.virtualHeight();
  if (width < 2 || height < 2) return;

  const float centerX = width >> 1;
  const float centerY = (height - 1) * 0.49f;
  const uint8_t beat = heartbeatLevel(strip.now, SEGMENT.speed);
  const float baseHalfHeight = 4.0f + (SEGMENT.custom1 * min(height * 0.24f, 2.8f) / 255.0f);
  const float pulseScale = 0.92f + beat * (0.13f / 255.0f);
  const float halfHeight = baseHalfHeight * pulseScale;
  const float halfWidth = min(width * 0.43f, baseHalfHeight * 0.86f) * pulseScale;
  const float glowReach = 0.035f + SEGMENT.intensity * (0.24f / 255.0f);
  const uint16_t period = 60000U / (42U + ((uint16_t)SEGMENT.speed * 78U >> 8));
  const float echoDistance = ((strip.now % period) * 0.42f) / period;
  const uint16_t colorTime = (strip.now * (8U + (SEGMENT.custom2 >> 3))) >> 7;

  for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
      const float dx = SEGMENT.wrap_x ? wrappedDelta(x, centerX, width) : x - centerX;
      bool carvedNotch;
      const float distance = heartDistance(dx, y - centerY, halfWidth, halfHeight, &carvedNotch);
      uint32_t color = flowingBackground(x, y, colorTime, 34);

      if (distance <= 0.0f) {
        const uint8_t depth = constrain(int(-distance * 720.0f), 0, 255);
        const uint8_t brightness = 165U + ((uint16_t)beat * 90U >> 8);
        const uint8_t paletteIndex = uint8_t(colorTime + x * 9 - y * 13 + depth);
        uint32_t heartColor = SEGMENT.color_from_palette(paletteIndex, false, true, 0, brightness);
        if (distance > -0.045f) heartColor = color_blend(heartColor, RGBW32(255, 235, 245, 0), 150);
        color = heartColor;
      } else {
        const int glow = carvedNotch ? 0 : 255 - int(distance * 255.0f / glowReach);
        if (glow > 0) {
          const uint8_t glowAmount = scale8_video(constrain(glow, 0, 255), 110U + (beat >> 1));
          const uint32_t glowColor = SEGMENT.color_from_palette(uint8_t(colorTime + x * 11), false, true, 0, glowAmount);
          color = color_blend(color, glowColor, glowAmount);
        }

        const float echoGap = fabsf(distance - echoDistance);
        if (!carvedNotch && echoGap < 0.035f) {
          const uint8_t echo = constrain(int((0.035f - echoGap) * 6200.0f), 0, 180);
          color = color_blend(color, SEGMENT.color_from_palette(uint8_t(colorTime + 96), false, true, 0), echo);
        }
      }
      SEGMENT.setPixelColorXY(x, y, color);
    }
  }
}

// Several small heart comets orbit the torso, bobbing vertically and leaving light trails.
const char LedWesteUsermod::mode_heart_orbit_str[] = "Heart Orbit@!,Trail,Hearts,Size,Bob;!,!;!;2;pal=11,sx=80,ix=180,c1=96,c2=150,c3=18";
void LedWesteUsermod::mode_heart_orbit()
{
  const int width = SEGMENT.virtualWidth();
  const int height = SEGMENT.virtualHeight();
  if (width < 2 || height < 2) return;

  const bool wrapX = SEGMENT.wrap_x;
  const uint8_t maxHearts = constrain(width / 7, 1, 4);
  const uint8_t heartCount = 1U + ((uint16_t)SEGMENT.custom1 * (maxHearts - 1U) + 127U) / 255U;
  const uint32_t travel = (strip.now * (18U + SEGMENT.speed)) >> 5;
  const uint16_t orbitBpm = 8U + (SEGMENT.speed >> 3);
  const uint16_t orbitPhase = beat16(orbitBpm);
  const float halfHeight = 2.2f + SEGMENT.custom2 * (1.9f / 255.0f);
  const float halfWidth = min(width * 0.30f, halfHeight * 0.88f);
  const float bobAmount = min(height * 0.22f, float(SEGMENT.custom3) * height / 124.0f);
  const uint16_t colorTime = strip.now >> 3;

  for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
      const uint8_t dust = qsub8(sin8_t(uint8_t(x * 37 + y * 61 + (strip.now >> 3))), 224);
      uint32_t color = flowingBackground(x, y, colorTime, 22U + (dust << 1));
      float closest = 10.0f;
      uint8_t closestHeart = 0;
      uint8_t trailLight = 0;
      bool closestNotch = false;

      for (uint8_t heart = 0; heart < heartCount; heart++) {
        const uint16_t phaseOffset = (uint32_t)heart * 65536U / heartCount;
        float centerX;
        if (wrapX) {
          const uint32_t spacing = (uint32_t)width * 256U / heartCount;
          centerX = ((travel + heart * spacing) % (width * 256U)) / 256.0f;
        } else {
          const uint16_t border = min(uint16_t(halfWidth + 0.5f), uint16_t((width - 1) >> 1));
          centerX = beatsin16_t(orbitBpm, border, width - 1 - border, 0, phaseOffset);
        }
        centerX = int(centerX + 0.5f); // keep the low-resolution cleft aligned to a pixel column
        const uint8_t bobPhase = uint8_t((strip.now >> 4) + heart * 83U);
        const float centerY = int((height - 1) * 0.50f + (int(sin8_t(bobPhase)) - 128) * bobAmount / 128.0f + 0.5f);
        const float dx = wrapX ? wrappedDelta(x, centerX, width) : x - centerX;
        bool carvedNotch;
        const float distance = heartDistance(dx, y - centerY, halfWidth, halfHeight, &carvedNotch);
        if (distance < closest) {
          closest = distance;
          closestHeart = heart;
          closestNotch = carvedNotch;
        }

        const bool movingRight = wrapX || cos16_t(orbitPhase + phaseOffset) >= 0;
        const float behind = movingRight ? -dx : dx;
        if (behind > 0.0f && behind < width * 0.48f) {
          const float verticalDistance = fabsf(y - centerY);
          if (verticalDistance < 1.2f) {
            const int trail = int((1.0f - behind / (width * 0.48f)) * (1.0f - verticalDistance / 1.2f) * SEGMENT.intensity);
            trailLight = max(trailLight, uint8_t(constrain(trail, 0, 255)));
          }
        }
      }

      if (trailLight) {
        const uint8_t trailIndex = uint8_t(colorTime + x * 9 + closestHeart * 67U);
        color = color_blend(color, SEGMENT.color_from_palette(trailIndex, false, true, 0, trailLight), trailLight);
      }
      if (closest <= 0.0f) {
        const uint8_t edge = constrain(int(-closest * 700.0f), 0, 255);
        const uint8_t paletteIndex = uint8_t(colorTime + closestHeart * 71U + edge);
        color = SEGMENT.color_from_palette(paletteIndex, false, true, 0, 210U + (edge * 45U >> 8));
        if (closest > -0.055f) color = color_blend(color, RGBW32(255, 245, 250, 0), 145);
      } else if (!closestNotch && closest < 0.12f) {
        const uint8_t glow = constrain(int((0.12f - closest) * 900.0f), 0, 108);
        color = color_blend(color, SEGMENT.color_from_palette(uint8_t(colorTime + closestHeart * 71U), false, true, 0), glow);
      }
      SEGMENT.setPixelColorXY(x, y, color);
    }
  }
}

// Sends luminous heart-shaped contours through the matrix like a neon topographic map.
const char LedWesteUsermod::mode_heart_echoes_str[] = "Heart Echoes@!,Brightness,Density,Flow,Size;!,!;!;2;pal=11,sx=66,ix=190,c1=150,c2=128,c3=19";
void LedWesteUsermod::mode_heart_echoes()
{
  const int width = SEGMENT.virtualWidth();
  const int height = SEGMENT.virtualHeight();
  if (width < 2 || height < 2) return;

  const float centerX = width >> 1;
  const float centerY = (height - 1) * 0.49f;
  const float halfHeight = height * (0.28f + SEGMENT.custom3 * (0.13f / 31.0f));
  const float halfWidth = min(width * 0.43f, halfHeight * 0.88f);
  const uint16_t timePhase = (strip.now * (10U + SEGMENT.speed)) >> 8;
  const float density = 300.0f + SEGMENT.custom1 * 2.4f;
  const uint8_t beat = heartbeatLevel(strip.now, SEGMENT.speed);

  for (int y = 0; y < height; y++) {
    for (int x = 0; x < width; x++) {
      const float dx = SEGMENT.wrap_x ? wrappedDelta(x, centerX, width) : x - centerX;
      bool carvedNotch;
      const float distance = heartDistance(dx, y - centerY, halfWidth, halfHeight, &carvedNotch);
      const int contourPhase = int(distance * density) - int(timePhase);
      const uint8_t contourWave = sin8_t(uint8_t(contourPhase));
      uint8_t contour = qsub8(contourWave, 178);
      contour = scale8_video(contour, SEGMENT.intensity);

      const uint8_t flowIndex = uint8_t(x * 11 - y * 9 + timePhase * (1U + (SEGMENT.custom2 >> 6)));
      uint32_t color = flowingBackground(x, y, timePhase, 26);
      if (distance > 0.0f && !carvedNotch && contour) {
        color = color_blend(color, SEGMENT.color_from_palette(flowIndex, false, true, 0, 150U + contour), min(255U, contour * 3U));
      }
      if (distance <= 0.0f) {
        const uint8_t fillBrightness = 180U + ((uint16_t)beat * 75U >> 8);
        color = SEGMENT.color_from_palette(uint8_t(flowIndex + 48), false, true, 0, fillBrightness);
      }
      if (fabsf(distance) < 0.025f) color = color_blend(color, RGBW32(255, 245, 250, 0), 180);
      SEGMENT.setPixelColorXY(x, y, color);
    }
  }
}
// AI: end

static LedWesteUsermod led_weste_usermod;
REGISTER_USERMOD(led_weste_usermod);
