#!/usr/bin/env node

'use strict';

const { createHash } = require('node:crypto');

// AI: below section was generated by an AI

function usage(message) {
  if (message) console.error(`Error: ${message}\n`);
  console.error(`Usage:
  node tools/sync_wled_presets.js --source <host-or-url> --target <host-or-url> [--target ...]
    [--require-preset-id <id>] [--scale-positioned-effects] [--allow-delete] [--apply]

The source defines preset and playlist behavior. Each target's live cfg.json
defines its matrix geometry. Dry-run is the default; --apply uploads and then
reads presets.json back for verification.

Only active segments covering the complete source matrix are transformed. The
script aborts on partial segments because scaling or clipping them would require
an explicit, device-specific policy. It also refuses to delete preset IDs already
present on a target unless --allow-delete is explicitly supplied.

--scale-positioned-effects additionally scales the coordinate controls of the
LedWeste Circle and Blinking Stripe effects. Use it when the target matrix has
different dimensions and those effects represent positioned garment lights.`);
  process.exit(message ? 1 : 0);
}

function parseArgs(argv) {
  const args = { source: '', targets: [], requiredPresetIds: [], scalePositionedEffects: false, allowDelete: false, apply: false };
  for (let i = 0; i < argv.length; i++) {
    switch (argv[i]) {
      case '--source':
        args.source = argv[++i] || '';
        break;
      case '--target':
        args.targets.push(argv[++i] || '');
        break;
      case '--apply':
        args.apply = true;
        break;
      case '--require-preset-id': {
        const id = Number(argv[++i]);
        if (!Number.isInteger(id) || id < 0 || id > 250) usage('--require-preset-id must be an integer from 0 to 250');
        args.requiredPresetIds.push(id);
        break;
      }
      case '--allow-delete':
        args.allowDelete = true;
        break;
      case '--scale-positioned-effects':
        args.scalePositionedEffects = true;
        break;
      case '--help':
      case '-h':
        usage();
        break;
      default:
        usage(`Unknown argument: ${argv[i]}`);
    }
  }
  if (!args.source) usage('--source is required');
  if (!args.targets.length || args.targets.some(target => !target)) usage('at least one non-empty --target is required');
  return args;
}

function baseUrl(hostOrUrl) {
  const value = /^https?:\/\//i.test(hostOrUrl) ? hostOrUrl : `http://${hostOrUrl}`;
  return value.replace(/\/$/, '');
}

async function fetchText(base, path) {
  const response = await fetch(`${base}${path}`, { signal: AbortSignal.timeout(8000) });
  if (!response.ok) throw new Error(`${base}${path}: HTTP ${response.status}`);
  return response.text();
}

function parseJson(text, description) {
  try {
    return JSON.parse(text);
  } catch (error) {
    throw new Error(`${description} is not valid JSON: ${error.message}`);
  }
}

// Derives the logical 2D canvas from panel placement rather than LED bus length.
function matrixDimensions(config, description) {
  const panels = config?.hw?.led?.matrix?.panels;
  if (!Array.isArray(panels) || !panels.length) throw new Error(`${description} has no matrix panel configuration`);

  let width = 0;
  let height = 0;
  for (const panel of panels) {
    const values = [panel.x, panel.y, panel.w, panel.h];
    if (!values.every(Number.isInteger) || panel.x < 0 || panel.y < 0 || panel.w <= 0 || panel.h <= 0) {
      throw new Error(`${description} has an invalid matrix panel`);
    }
    width = Math.max(width, panel.x + panel.w);
    height = Math.max(height, panel.y + panel.h);
  }
  return { width, height };
}

function forEachActiveSegment(presets, callback) {
  let count = 0;
  for (const [presetId, preset] of Object.entries(presets)) {
    if (!Array.isArray(preset?.seg)) continue;
    for (const segment of preset.seg) {
      if (!segment || !Number.isInteger(segment.stop) || segment.stop <= (segment.start ?? 0)) continue;
      callback(segment, presetId);
      count++;
    }
  }
  return count;
}

function scaledControl(value, numerator, denominator) {
  return Math.max(0, Math.min(255, Math.round(value * numerator / denominator)));
}

// Scales controls that the LedWeste effects interpret as logical matrix coordinates.
function adaptPositionedEffect(segment, effectName, sourceMatrix, targetMatrix, presetId, targetName) {
  if (sourceMatrix.width === targetMatrix.width && sourceMatrix.height === targetMatrix.height) return false;

  if (effectName === 'Blinking Stripe') {
    if (![segment.c1, segment.c2].every(Number.isInteger)) {
      throw new Error(`${targetName}: preset ${presetId} Blinking Stripe has invalid Begin/End controls`);
    }
    segment.c1 = scaledControl(segment.c1, targetMatrix.width, sourceMatrix.width);
    segment.c2 = scaledControl(segment.c2, targetMatrix.width, sourceMatrix.width);
    return true;
  }

  if (effectName === 'Circle') {
    if (![segment.c1, segment.c2, segment.c3].every(Number.isInteger)) {
      throw new Error(`${targetName}: preset ${presetId} Circle has invalid center/radius controls`);
    }
    segment.c1 = scaledControl(segment.c1, targetMatrix.width, sourceMatrix.width);
    segment.c2 = scaledControl(segment.c2, targetMatrix.height, sourceMatrix.height);
    const widthScaledRadius = segment.c3 * targetMatrix.width / sourceMatrix.width;
    const heightScaledRadius = segment.c3 * targetMatrix.height / sourceMatrix.height;
    segment.c3 = Math.max(0, Math.min(31, Math.round(Math.min(widthScaledRadius, heightScaledRadius))));
    return true;
  }

  return false;
}

// Copies behavior while adapting full-matrix bounds and explicitly supported coordinates.
function adaptPresets(sourcePresets, sourceMatrix, targetMatrix, targetName, effectNames, scalePositionedEffects) {
  const result = structuredClone(sourcePresets);
  let positionedCount = 0;
  const count = forEachActiveSegment(result, (segment, presetId) => {
    const bounds = {
      start: segment.start ?? 0,
      stop: segment.stop,
      startY: segment.startY ?? 0,
      stopY: segment.stopY
    };
    const isFullMatrix = bounds.start === 0 &&
      bounds.stop === sourceMatrix.width &&
      bounds.startY === 0 &&
      bounds.stopY === sourceMatrix.height;
    if (!isFullMatrix) {
      throw new Error(
        `${targetName}: preset ${presetId} has bounds ` +
        `${bounds.start},${bounds.startY}..${bounds.stop},${bounds.stopY}; ` +
        `expected full source matrix 0,0..${sourceMatrix.width},${sourceMatrix.height}`
      );
    }
    segment.start = 0;
    segment.stop = targetMatrix.width;
    segment.startY = 0;
    segment.stopY = targetMatrix.height;
    if (scalePositionedEffects && adaptPositionedEffect(segment, effectNames[segment.fx], sourceMatrix, targetMatrix, presetId, targetName)) {
      positionedCount++;
    }
  });
  if (!count) throw new Error('source presets contain no active matrix segments');
  return { presets: result, segmentCount: count, positionedCount };
}

function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`;
  }
  return JSON.stringify(value);
}

function sha256(text) {
  return createHash('sha256').update(text).digest('hex');
}

function presetIds(presets, description) {
  const ids = Object.keys(presets).map(key => Number(key));
  if (ids.some(id => !Number.isInteger(id) || id < 0 || id > 250)) {
    throw new Error(`${description} contains a non-numeric or out-of-range preset key`);
  }
  return ids.sort((left, right) => left - right);
}

function validatePlaylistReferences(presets, description) {
  const ids = new Set(presetIds(presets, description));
  for (const [presetId, preset] of Object.entries(presets)) {
    const references = preset?.playlist?.ps;
    if (!Array.isArray(references)) continue;
    const missing = references.filter(id => Number.isInteger(id) && !ids.has(id));
    if (missing.length) throw new Error(`${description} playlist ${presetId} references missing presets: ${[...new Set(missing)].join(', ')}`);
  }
}

async function uploadPresets(base, text) {
  const form = new FormData();
  form.append('data', new Blob([text], { type: 'application/json' }), '/presets.json');
  const response = await fetch(`${base}/upload`, {
    method: 'POST',
    body: form,
    signal: AbortSignal.timeout(15000)
  });
  if (!response.ok) throw new Error(`${base}/upload: HTTP ${response.status}: ${await response.text()}`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const sourceBase = baseUrl(args.source);
  const sourcePresetText = await fetchText(sourceBase, '/presets.json');
  const [sourcePresets, sourceConfig, sourceEffectNames] = await Promise.all([
    Promise.resolve(parseJson(sourcePresetText, `${sourceBase}/presets.json`)),
    fetchText(sourceBase, '/cfg.json').then(text => parseJson(text, `${sourceBase}/cfg.json`)),
    args.scalePositionedEffects
      ? fetchText(sourceBase, '/json/effects').then(text => parseJson(text, `${sourceBase}/json/effects`))
      : Promise.resolve([])
  ]);
  if (args.scalePositionedEffects && !Array.isArray(sourceEffectNames)) {
    throw new Error(`${sourceBase}/json/effects is not an array`);
  }
  const sourceMatrix = matrixDimensions(sourceConfig, sourceBase);
  const sourceIds = new Set(presetIds(sourcePresets, `${sourceBase}/presets.json`));
  validatePlaylistReferences(sourcePresets, `${sourceBase}/presets.json`);
  for (const id of args.requiredPresetIds) {
    if (!sourceIds.has(id)) throw new Error(`${sourceBase}/presets.json is missing required preset ${id}`);
  }

  const targets = await Promise.all(args.targets.map(async target => {
    const base = baseUrl(target);
    const [configText, existingPresetText] = await Promise.all([
      fetchText(base, '/cfg.json'),
      fetchText(base, '/presets.json')
    ]);
    const existingPresets = parseJson(existingPresetText, `${base}/presets.json`);
    if (!args.allowDelete) {
      const deletedIds = presetIds(existingPresets, `${base}/presets.json`).filter(id => !sourceIds.has(id));
      if (deletedIds.length) {
        throw new Error(`${base}: source would delete preset IDs ${deletedIds.join(', ')}; repair the source or pass --allow-delete`);
      }
    }
    const matrix = matrixDimensions(parseJson(configText, `${base}/cfg.json`), base);
    const adapted = adaptPresets(sourcePresets, sourceMatrix, matrix, base, sourceEffectNames, args.scalePositionedEffects);
    const text = matrix.width === sourceMatrix.width && matrix.height === sourceMatrix.height
      ? sourcePresetText
      : JSON.stringify(adapted.presets);
    return { base, matrix, text, segmentCount: adapted.segmentCount, positionedCount: adapted.positionedCount, presets: adapted.presets };
  }));

  console.log(`Source ${sourceBase}: ${sourceMatrix.width}x${sourceMatrix.height}, ` +
    `${sourceIds.size} presets, sha256=${sha256(sourcePresetText)}`);
  for (const target of targets) {
    console.log(`Target ${target.base}: ${target.matrix.width}x${target.matrix.height}, ` +
      `${target.segmentCount} segments, ${target.positionedCount} positioned effects, sha256=${sha256(target.text)}`);
  }

  if (!args.apply) {
    console.log('Dry run only; pass --apply to upload these variants.');
    return;
  }

  for (const target of targets) {
    await uploadPresets(target.base, target.text);
    const actualText = await fetchText(target.base, '/presets.json');
    const actual = parseJson(actualText, `${target.base}/presets.json after upload`);
    if (stableJson(actual) !== stableJson(target.presets)) {
      throw new Error(`${target.base}: uploaded presets failed semantic read-back verification`);
    }
    console.log(`Verified ${target.base}: uploaded presets match its geometry-specific variant`);
  }
}

main().catch(error => {
  console.error(`Preset synchronization failed: ${error.message}`);
  process.exitCode = 1;
});

// AI: end
